# Generated by Django 4.0.1 on 2022-04-13 14:19

from django.db import migrations, models
import storage.custom_azure


class Migration(migrations.Migration):

    dependencies = [
        ('answer_script', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerscript',
            name='script',
            field=models.FileField(blank=True, null=True, storage=storage.custom_azure.AzureMediaStorage, upload_to='answer_scripts/'),
        ),
    ]
